### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by hiroshihorie**

### CODE REVIEW

**Comment by hiroshihorie** [comment]
progress is stuck until I figure out how to compile on a M1 Mac....

**Comment by hiroshihorie** [comment]
@davidliu found that actually VS 2022 has issues https://github.com/flutter/flutter/issues/85922
I was getting the same error so i thought it was an ARM Windows compile issue but I'm not sure now 😅
(could be both)
https://github.com/flutter/flutter/issues/53120

**Comment by ashellunts** [comment]
VS 2022 is coming to flutter 2.9. I will try to find if 2019 is available online.

**Comment by ashellunts** [comment]
Link to download VS 2019
https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=community&rel=16

**Review by davidzhao — APPROVED** [review]
awesome work!

**Pull request merged**
