### PR TITLE
Fix mute/unmute on Windows

### PR DESCRIPTION
**Pull request by ashellunts**
ReplaceTrack is not implemented in flutter_webrtc.

### CODE REVIEW

**Comment by hiroshihorie** [comment]
This will break other platforms can you wrap it with windows platform check? 😁

**Comment by ashellunts** [comment]
> This will break other platforms can you wrap it with windows platform check? 😁

Done

**Review by hiroshihorie — APPROVED** [review]
✅ lgtm, but the root issue is that replaceTrack is not implemented yet in Windows ?

**Comment by ashellunts** [comment]
> ✅ lgtm, but the root issue is that replaceTrack is not implemented yet in Windows ?

Yes. We can implement it later.

**Pull request merged**
