### PR TITLE
Apply Flutter best practices [Non-Breaking]

### PR DESCRIPTION
**Pull request by hiroshihorie**
Add [flutter_lints](https://pub.dev/packages/flutter_lints) package, and clear the lint warnings.
This PR is intended to be **non-breaking**, but  clearing some lint errors **need breaking changes**, I will open another Draft PR for that.

### CODE REVIEW

**Comment by hiroshihorie** [comment]
@davidzhao The tests wont pass because I didn't solve the "Prefer using lowerCamelCase for constant names" lint which requires **potentially breaking changes**.

**Comment by davidzhao** [comment]
Ah I see. could we turn off this rule? Some of those we'd probably want to preserve, like `RTCIceTransportPolicyAll`

Do you have ideas around handling the print violations in example? should we ignore that folder entirely?

**Comment by hiroshihorie** [comment]
@davidzhao  IMO that should be an **enum** maybe something like:

```dart
enum RTCIceTransportPolicy {
  all,
  relay,
}

extension RTCIceTransportPolicyExt on RTCIceTransportPolicy {
  String toStringValue() => {
    RTCIceTransportPolicy.all: 'all',
    RTCIceTransportPolicy.relay: 'relay',
  }[this]!;
}
```

But that's potentially breaking, I don't see references to `RTCIceTransportPolicyAll` and `RTCIceTransportPolicyRelay` as of now tho.

**Comment by davidzhao** [comment]
that's fair. go ahead and update to your suggestions. Since we haven't officially released it *and* none of these enums are in the critical path, it's fine to not maintain compatibility.

**Review by davidzhao — APPROVED** [review]
looks good!

**Comment by hiroshihorie** [comment]
I find the 80 chars line length too short for `flutter format`, can we set it to **120**?
https://github.com/dart-lang/dart_style/issues/833

`flutter format --set-exit-if-changed -l 120 .`

**Comment by davidzhao** [comment]
I'm ok with relaxing the constraints a bit. But I think 120 is a bit too long. How about 100?

**Comment by hiroshihorie** [comment]
@davidzhao Made minor improvements to the example

**Pull request merged**
