### PR TITLE
re/livekit_client/livekit

### PR DESCRIPTION
**Pull request by ashellunts**

### CODE REVIEW

**Comment by hiroshihorie** [comment]
We cannot change the package name it's already published 🙂
https://pub.dev/packages/livekit_client

**Comment by ashellunts** [comment]
In that case I think we can't rename `livekit_client_plugin` to `livekit_plugin`.

**Comment by hiroshihorie** [comment]
Ok no problem then 🙂 as long as there are no compile issues.

**Comment by hiroshihorie** [comment]
Thanks for trying to make it consistent with other plugin names 🙂

**Pull request closed without merging**
