### PR TITLE
fix(connect): await engine.connect in async context

### PR DESCRIPTION
**Pull request by isqad**

### CODE REVIEW

**Comment by davidzhao** [comment]
@isqad I believe both approaches are identical. we are returning a Future<void> from `connect`. Am I missing anything?

**Comment by isqad** [comment]
I though that `async` modificator is not needed if no any `await` calls 🤔

**Comment by davidzhao** [comment]
> I though that `async` modificator is not needed if no any `await` calls 🤔

that's true :) but having it is also a valid syntax.

**Comment by isqad** [comment]
> but having it is also a valid syntax.

Ok) So this PR might be closed)

**Comment by hiroshihorie** [comment]
Thanks @isqad I understand this looked weird, in the process of making this PR https://github.com/livekit/client-sdk-flutter/pull/109/files that code has been modified to be more clean.

**Comment by isqad** [comment]
All right, It is become more clear for me, thank you!

**Pull request closed without merging**
